services:
- docker
env:
  global:
  - FLASK_APP=todo_app.app
  - FLASK_ENV=production
  - secure: IM8D2CYyPOwYihG14eV5Vkg74xu9LuWIIK1UZl4wUx7MKAj/1J25Yhmlc4WQzBoQO+ZYm4h/mMaqAf6K5KGcJzSSbDcUTS618VZnhRBoF5hvMSWJdH4v8WvkAVZ29Tk9LkJHu32ARr/GpZxGmHAIHS4SJ8FWu04BF831x9swV0vWVa8X+Ggh61egdwyWXh4CnKZTk9jKf7FArv9DbtSUnStoylgZeIuC4/MU8rmmOy4DBEv3kD7EfnAuT4hVuV4790j/BNkR4sYOldu+wFvTFTZTP/ftcdZIUDKHWneev/YDZoMCwrcVUld/atiQOwwcNxq2b8E1PsEsHsogV2cPF1B7I6J8UPbip7mjoD2ly1gXm0KVE3nijdI4HFEcx7p6b++IpFWkAL9ZMSS5AGyv6W+pi6vzoeVNaZvCo46Cmu/ZJ4GB6lF98AoBJboy1R/aMVjgCIwfJdXCgcjQDHjPFWZHXJF25b88hQSFk502AzzijFc0DUwc4q/KrZx/m/XnIIHBnK02AzlzwHV23zV7kXdszNli6s1XXjMVZZZsCBmDZYmwJ5WnbketT6k2WXarlLRkqEx46fGTCWo1X5TQuqXgdPcUYzIT/A2sHJwvCSZ0KYhfQ7KccL1N6KMKCKOA9sfH0K88V8d+nAkHEQS0/FV2PmWgtBhgYRb1nicVxYg=
  - DATABASE_NAME=tododb
before_script:
- docker login -u rysharp -p $DOCKERHUB_PW
- docker login -u=_ -p=$HEROKU_API_KEY registry.heroku.com
script:
- docker build --target test -t todo-app .
- docker run todo-app todo_app/tests/
- docker run todo_app/tests_e2e/
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
notifications:
  email: false
