script:
  - docker build --target test -t todo-app .
  - docker run --env API_KEY --env API_TOKEN --env API_SECRET --env BOARD_ID --env FLASK_APP --env FLASK_ENV todo-app
notifications:
  email: false