version: "3.9"

services:
  todo_app:
    container_name: todo_app
    image: todo-app:dev
    env_file:
      - .env
    ports:
    - 5000:5000
    volumes:
    - type: bind
      source: ./todo_app
      target: /app/todo_app
      read_only: true